import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { create, getByRealPlant, getAll, deleteUpdate } from "./plantUpdate.controller.js";
import { createPlantUpdateSchema } from "./plantUpdate.schema.js";
const router = Router();
router.get("/all", authenticate, authorize("ADMIN", "FARMER"), getAll);
router.post("/", authenticate, authorize("FARMER"), validateBody(createPlantUpdateSchema), create);
router.get("/:realPlantId", authenticate, getByRealPlant);
router.delete("/:id", authenticate, authorize("ADMIN"), deleteUpdate);
export default router;
