import { Router } from "express";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { register, login, getMe, updateProfile, updatePassword, refresh, logout, } from "./auth.controller.js";
import { registerSchema, loginSchema, updateProfileSchema, updatePasswordSchema, } from "./auth.schema.js";
const router = Router();
router.post("/register", validateBody(registerSchema), register);
router.post("/login", validateBody(loginSchema), login);
router.get("/me", authenticate, getMe);
router.patch("/update-profile", authenticate, validateBody(updateProfileSchema), updateProfile);
router.patch("/update-password", authenticate, validateBody(updatePasswordSchema), updatePassword);
router.post("/refresh", refresh);
router.post("/logout", logout);
export default router;
