import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { audioUpload, uploadTrackHandler, listTracksHandler, getTrackByIdHandler, updateTrackHandler, deleteTrackHandler, getSignedUrlHandler, getUploadUrlHandler, createTrackHandler, } from "./calmMusic.controller.js";
const router = Router();
router.post("/upload", authenticate, authorize("ADMIN"), audioUpload.single("audio"), uploadTrackHandler);
router.post("/upload-url", authenticate, authorize("ADMIN"), getUploadUrlHandler);
router.post("/track", authenticate, authorize("ADMIN"), createTrackHandler);
router.get("/", authenticate, listTracksHandler);
router.get("/:id", authenticate, getTrackByIdHandler);
router.patch("/:id", authenticate, authorize("ADMIN"), updateTrackHandler);
router.delete("/:id", authenticate, authorize("ADMIN"), deleteTrackHandler);
router.get("/:id/signed-url", authenticate, getSignedUrlHandler);
export default router;
