import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { getActivePlans, getMyCurrentPlan, getMyEntitlements, createOrderHandler, getMyOrders, getOrderByIdHandler, subscribeVirtualPlus, updateOrderShippingInfoHandler, adminGetPlans, adminCreatePlan, adminUpdatePlan, adminTogglePlanActive, adminGetOrders, adminGetOrderById, adminConfirmPaymentHandler, adminUpdateOrderStatusHandler, adminUpdateShippingStatusHandler, adminGetAvailableRealPlants, adminAssignRealPlantHandler, adminGetUserCurrentPlan, } from "./servicePlan.controller.js";
const router = Router();
router.get("/plans", getActivePlans);
router.get("/plans/my-current", authenticate, getMyCurrentPlan);
router.get("/me/entitlements", authenticate, getMyEntitlements);
router.post("/orders", authenticate, createOrderHandler);
router.get("/orders/my", authenticate, getMyOrders);
router.get("/orders/:id", authenticate, getOrderByIdHandler);
router.post("/subscriptions/virtual-plus", authenticate, subscribeVirtualPlus);
router.patch("/orders/:id/shipping-info", authenticate, updateOrderShippingInfoHandler);
router.get("/admin/plans", authenticate, authorize("ADMIN"), adminGetPlans);
router.get("/admin/users/:id/current-plan", authenticate, authorize("ADMIN"), adminGetUserCurrentPlan);
router.post("/admin/plans", authenticate, authorize("ADMIN"), adminCreatePlan);
router.patch("/admin/plans/:id", authenticate, authorize("ADMIN"), adminUpdatePlan);
router.patch("/admin/plans/:id/toggle-active", authenticate, authorize("ADMIN"), adminTogglePlanActive);
router.get("/admin/orders", authenticate, authorize("ADMIN"), adminGetOrders);
router.get("/admin/orders/:id", authenticate, authorize("ADMIN"), adminGetOrderById);
router.patch("/admin/orders/:id/confirm-payment", authenticate, authorize("ADMIN"), adminConfirmPaymentHandler);
router.patch("/admin/orders/:id/status", authenticate, authorize("ADMIN"), adminUpdateOrderStatusHandler);
router.patch("/admin/orders/:id/shipping-status", authenticate, authorize("ADMIN"), adminUpdateShippingStatusHandler);
router.get("/admin/real-plants/available", authenticate, authorize("ADMIN"), adminGetAvailableRealPlants);
router.patch("/admin/orders/:id/assign-real-plant", authenticate, authorize("ADMIN"), adminAssignRealPlantHandler);
export default router;
