import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { start, getMy, getOne, getTimeline, updateNickname, carePlant, getAllAdmin, harvestPlant } from "./virtualPlant.controller.js";
import { startVirtualPlantSchema, updateNicknameSchema } from "./virtualPlant.schema.js";
const router = Router();
router.post("/start", authenticate, authorize("USER"), validateBody(startVirtualPlantSchema), start);
router.get("/all", authenticate, authorize("ADMIN"), getAllAdmin);
router.get("/my", authenticate, getMy);
router.get("/:id", authenticate, getOne);
router.get("/:id/timeline", authenticate, getTimeline);
router.patch("/:id", authenticate, validateBody(updateNicknameSchema), updateNickname);
router.post("/:id/care", authenticate, carePlant);
router.post("/:id/harvest", authenticate, authorize("USER"), harvestPlant);
export default router;
