import { Router } from "express";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { uploadCharacter, uploadTaskPhoto } from "../../middlewares/upload.middleware.js";
import { getAll, create, updateTask, uploadCharacterImage, deleteCharacterImage, completeTask, getMyLogs, } from "./careTask.controller.js";
import { updateCareTaskSchema } from "./careTask.schema.js";
const router = Router();
router.get("/", authenticate, getAll);
router.post("/", authenticate, uploadCharacter.single("image"), create);
router.patch("/:id", authenticate, updateTask);
router.post("/:id/character-image", authenticate, uploadCharacter.single("image"), uploadCharacterImage);
router.delete("/:id/character-image", authenticate, deleteCharacterImage);
router.post("/logs", authenticate, uploadTaskPhoto.single("photo"), completeTask);
router.get("/logs/my", authenticate, getMyLogs);
export default router;
