import { Router } from "express";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { create, getMy, getById, remove } from "./moodJournal.controller.js";
import { createMoodJournalSchema } from "./moodJournal.schema.js";
const router = Router();
router.post("/", authenticate, validateBody(createMoodJournalSchema), create);
router.get("/my", authenticate, getMy);
router.get("/:id", authenticate, getById);
router.delete("/:id", authenticate, remove);
export default router;
