import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { getAllUsers, toggleActive, savePushToken, getUserVirtualPlants, getUserRealPlants, getUserMoodJournals, getMyFlowerGarden } from "./user.controller.js";
const router = Router();
router.patch("/push-token", authenticate, savePushToken);
router.get("/me/flower-garden", authenticate, authorize("USER"), getMyFlowerGarden);
router.use(authenticate, authorize("ADMIN"));
router.get("/", getAllUsers);
router.get("/:id/virtual-plants", getUserVirtualPlants);
router.get("/:id/real-plants", getUserRealPlants);
router.get("/:id/mood-journals", getUserMoodJournals);
router.patch("/:id", toggleActive);
export default router;
