import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { getAll, getOne, create, update, remove } from "./flowerType.controller.js";
import { createFlowerTypeSchema, updateFlowerTypeSchema } from "./flowerType.schema.js";
const router = Router();
router.get("/", getAll);
router.get("/:id", getOne);
router.post("/", authenticate, authorize("ADMIN"), validateBody(createFlowerTypeSchema), create);
router.put("/:id", authenticate, authorize("ADMIN"), validateBody(updateFlowerTypeSchema), update);
router.delete("/:id", authenticate, authorize("ADMIN"), remove);
export default router;
