import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { getPosts, getPostById, toggleReaction, reportPost, deletePost, hidePost, setPostVisible, getAllAdmin, } from "./community.controller.js";
const router = Router();
router.get("/posts", authenticate, getPosts);
router.get("/posts/:id", authenticate, getPostById);
router.post("/posts/:id/reactions", authenticate, toggleReaction);
router.post("/posts/:id/report", authenticate, reportPost);
router.delete("/posts/:id", authenticate, deletePost);
router.get("/admin/posts", authenticate, authorize("ADMIN"), getAllAdmin);
router.patch("/admin/posts/:id/hide", authenticate, authorize("ADMIN"), hidePost);
router.patch("/admin/posts/:id/visible", authenticate, authorize("ADMIN"), setPostVisible);
export default router;
