import { Router } from "express";
import { authenticate } from "../../middlewares/auth.middleware.js";
import { getMyNotifications, markRead, markAllRead } from "./notification.controller.js";
const router = Router();
router.get("/my", authenticate, getMyNotifications);
router.patch("/:id/read", authenticate, markRead);
router.patch("/read-all", authenticate, markAllRead);
import { testFcm, registerFcmToken } from "./notification.controller.js";
router.post("/register-token", authenticate, registerFcmToken);
router.post("/test-fcm", authenticate, testFcm);
export default router;
