import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { getAll, getOne, create, update, approve, reject, remove, getPlantSummary } from "./garden.controller.js";
import { createGardenSchema, updateGardenSchema } from "./garden.schema.js";
const router = Router();
router.get("/", authenticate, authorize("ADMIN", "FARMER"), getAll);
router.get("/:id/plant-summary", authenticate, authorize("ADMIN", "FARMER"), getPlantSummary);
router.get("/:id", getOne);
router.post("/", authenticate, authorize("ADMIN", "FARMER"), validateBody(createGardenSchema), create);
router.put("/:id", authenticate, authorize("ADMIN", "FARMER"), validateBody(updateGardenSchema), update);
router.patch("/:id/approve", authenticate, authorize("ADMIN"), approve);
router.patch("/:id/reject", authenticate, authorize("ADMIN"), reject);
router.delete("/:id", authenticate, authorize("ADMIN"), remove);
export default router;
