import { Router } from "express";
import { authenticate, authorize } from "../../middlewares/auth.middleware.js";
import { validateBody } from "../../middlewares/validate.middleware.js";
import { getAll, getOne, create, update, batchCreate } from "./realPlant.controller.js";
import { createRealPlantSchema, updateRealPlantSchema } from "./realPlant.schema.js";
import { reactToPlant, getReactions, addComment, getComments, deleteComment, getFeedbackSummary, } from "./plantFeedback.controller.js";
const router = Router();
router.get("/", authenticate, authorize("ADMIN", "FARMER"), getAll);
router.post("/batch", authenticate, authorize("ADMIN", "FARMER"), batchCreate);
router.get("/feedback-summary", authenticate, authorize("ADMIN", "FARMER"), getFeedbackSummary);
router.get("/:id", authenticate, authorize("ADMIN", "FARMER"), getOne);
router.post("/", authenticate, authorize("ADMIN", "FARMER"), validateBody(createRealPlantSchema), create);
router.put("/:id", authenticate, authorize("ADMIN", "FARMER"), validateBody(updateRealPlantSchema), update);
router.post("/:id/react", authenticate, reactToPlant);
router.get("/:id/reactions", authenticate, getReactions);
router.post("/:id/comments", authenticate, addComment);
router.get("/:id/comments", authenticate, getComments);
router.delete("/:id/comments/:commentId", authenticate, deleteComment);
export default router;
